/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentAgentIdRouteImport } from './routes/agent.$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/cron': typeof CronRoute
  '/settings': typeof SettingsRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/cron': typeof CronRoute
  '/settings': typeof SettingsRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/cron': typeof CronRoute
  '/settings': typeof SettingsRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/chat'
    | '/cron'
    | '/settings'
    | '/agent/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/channels' | '/chat' | '/cron' | '/settings' | '/agent/$agentId'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/chat'
    | '/cron'
    | '/settings'
    | '/agent/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  ChatRoute: typeof ChatRoute
  CronRoute: typeof CronRoute
  SettingsRoute: typeof SettingsRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  ChatRoute: ChatRoute,
  CronRoute: CronRoute,
  SettingsRoute: SettingsRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
